language: node_js
node_js:
- stable
env:
- DISPLAY=:99.0
services:
  - xvfb
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build:prod
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
deploy:
  skip_cleanup: true
  provider: npm
  email: davis_france@hotmail.com
  api_key:
      secure: l0wmjJK6CwfpKAn/+Lzyym4hdvYCgEUJSIy+MNNfhqeEB5c+mj5GEei0uVpj+YSdCQiRSztzKBQDKjP5HSbjwxtfMQL/zBfUjz7cum1Gg4858tm2EhmWvM67OIn6Ft5iVHlzubZbbR7UN2kzKAYDZKsVaTuZEhx9KjhVTFjvdkHsNpzWOw42tLc0ILAEjci9DmxJZ7wilMYGA7OYZi98QHc7JT/IpI8p2qH5uQ157YDsfrxrTKdME0wzIS1NvqXT2iKen2QlwF49TpSknLKToUoQkvZQ58AZcgzQHXtQd5FuungrOT/ePXvmBwOHHJhVYLW1roZoYngaOC7wQnoQrWmzn54CpS6vIK59JOxCWXKt8wOf5tty8kRk2pa8p7wAV6VAOkPbvZJGsDhw9RqNQaxC7hgf27lEGKuK/hicGQzWqGL181CNBAD0sg1Ha+Qhh0LG92sYyLCSdZybfHL6sW5YGDjQetFETT1NsKeNwNZUHvcdsPuPYFZtfi8qFo7KpKMJxiE0GzI0vPPGcahFbnWb9K1+38GueEkMEsAYJekUasCQsd0Zs4BXLzYtb2dpiOTi62iSYe/QAB354e7tptLYJ/KO0U8Dc7LN851LCfEwBgzXULi1/GREuYA=
  on:
    tags: true
