language: node_js
node_js:
- stable
env:
- DISPLAY=:99.0
services:
  - xvfb
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build:prod
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
deploy:
  skip_cleanup: true
  provider: npm
  email: davis_france@hotmail.com
  api_key:
    secure: "Od0Pt6ddDAiFINo/hYtOGXa5KpTdbHSREhVkJ9nvZPCAUfqy3kPzz7QWKbk/sYrsb5/ehoZaTP+DkhFcrau23iwybWKzff4KLoFB8yhR5H93P6+H2sUfCOfGDpQWgSHgdfjCyzTwfSXqrgt+Ej+NtLxC8KnkJRmLO91PGZZ8pDRO3FPIBEes1JuHDaHni1H7vsvJQ/oUpIx1dgRlQdLOA5N18BKfSt939165+RUGmynhcU5YWNSr4GDwjK4Rw4wyHyLniZArP5DUBxIeyArHRJ6/EO85kJMweDJ2crM//dWQeCrgiX8sWhMpyEBK0NcFQ7s3OVpquLW+VyGJMBkF6diJooa7YfcJzFO9aABPk7s8b4KNIpLaK+0e+oWND9/P4YiBHfoqmgzg3drxpTqScd+fs1YRINRc3jbkBI+HKwE3pcyOdj2DzIWzwiLWH+q8W2RA1dDiLilK+5LbOGdKUoO926Kf1HLf7QewrQK2JihS7YJ0BQtnDOHT+AfiIhMBKQUNLCCUSK9jDtYahZUqrWuDEoqmO8/wvXjYMgaFvQ1zBiGI5eUX4iJg7t6Nt1bHm1965h5X45OHLiiCAAhZSn6rZDAk5meZmukOs70P2WDJDCxCw9Jfm62SIO1vD0ARH3QQf+9osnqtIspw0v1LciO9OIdbDNlz4QIFVGKQtsA="
  on:
    tags: true
